apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-game-server-abbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-game-server-abbs
    app.kubernetes.io/part-of: shipwars
  name: shipwars-game-server-abbs
  namespace: eshortis-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shipwars-game-server-abbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shipwars-game-server-abbs
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: Stone Soup
        image: quay.io/redhat-appstudio/user-workload@sha256:b7a78bbccabbdb00d64356aa8e92644e7097b69a1aa5da5f34a91a9595b38036
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
