apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shipwars-game-server-abbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shipwars-game-server-abbs
    app.kubernetes.io/part-of: shipwars
  name: shipwars-game-server-abbs
  namespace: eshortis-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: shipwars-game-server-abbs
status:
  loadBalancer: {}
